#! /usr/bin/env python


'''
Write in the stdout the configuration of templated and non templated 
monitor points generated by thei plugin

The initial part of the plugin configuration is not generated by this script
'''

refreshTime="60000"

mPointJSonPrefix= '{"id":"'
mPointJSonSuffix= '", "refreshTime":"%s", "filter":"", "filterOptions":""}' % (refreshTime)

nonTemplatedPointIds = [
    'Array-Laser-Locked'
]

baseIds = [
    "Array-CRIO-TEMP0-",
    "Array-CRIO-TEMP5-",
    "Array-CRIO-TEMP9-",
    "Array-CRIO-VACUUM-PRES0-",
    "Array-CRIO-VACUUM-PRES1-",
    "Array-CMPR-DRIVE-"
]

mPointJSonPrefix= '{"id":"'
mPointJSonSuffix= '", "refreshTime":"%s", "filter":"", "filterOptions":""}' % (refreshTime)

def buildAntennaNames():

    DV = range(1,26)
    DA = range(41,66)
    PM = range(1,5)
    CM = range(1,13)

    templatePrefix="[!#"
    templateSuffix= "!]"

    ret = []
    for i in DV:
        ret.append('DV%s%d%s' % (templatePrefix, i, templateSuffix))
    for i in DA:
        ret.append('DA%s%d%s' % (templatePrefix, i, templateSuffix))
    for i in PM:
        ret.append('PM%s%d%s' % (templatePrefix, i, templateSuffix))
    for i in CM:
        ret.append('CM%s%d%s' % (templatePrefix, i, templateSuffix))
    return ret

if __name__=="__main__":
    print '  ['

    for id in nonTemplatedPointIds:
        print '    %s%s%s' % (mPointJSonPrefix, id, mPointJSonSuffix),

    antNames=buildAntennaNames()
    for name in  antNames:
        for id in baseIds:
             print ','
             print '    %s%s%s%s' % (mPointJSonPrefix, id, name, mPointJSonSuffix),
    
    print '\n  ]'
