FROM centos:7
RUN yum update -y && \
  yum install java-1.8.0-openjdk-devel \
  wget \
  nmap-ncat \
  -y
WORKDIR /usr/src/dummy_plugin
COPY dist/dummy-plugin.jar /usr/src/dummy_plugin/dummy-plugin.jar
ENTRYPOINT ["java", "-jar", "dummy-plugin.jar"]
