version: "2"

services:
    alma-weather-plugin:
        image: alma-weather-plugin:latest
        links:
            - "kafka"
    kafka:
        image: spotify/kafka:latest
        ports:
            - "9092:9092"
            - "2181:2181"
