FROM openjdk:8-jdk-alpine
RUN apk update && apk add netcat-openbsd wget
WORKDIR /usr/src/alma_weather_plugin
COPY dist/alma-weather-station-plugin.jar /usr/src/alma_weather_plugin/alma-weather-station-plugin.jar
COPY config.json /usr/src/alma_weather_plugin/
COPY entrypoint.sh /usr/src/alma_weather_plugin
ENTRYPOINT ["./entrypoint.sh"]
