FROM centos:7
RUN yum update -y && \
  yum install java-1.8.0-openjdk-devel \
  -y
ENV JAVA_HOME /usr/lib/jvm/java-1.8.0-openjdk
# --------------------------------------
# Install Gradle
# --------------------------------------
WORKDIR /usr/src/weather_visual_inspection_plugin/src
COPY gradlew .
COPY gradle ./gradle
COPY gradle.properties .
COPY settings.gradle .
COPY build.gradle .
RUN ./gradlew

# --------------------------------------
# Build Project
# --------------------------------------
COPY . .
RUN rm -rf dist
RUN mkdir dist
RUN ./gradlew build --refresh-dependencies

# --------------------------------------
# Move JARs and Clean
# --------------------------------------
WORKDIR /usr/src/weather_visual_inspection_plugin
RUN mv src/dist/weather-visual-inspection-plugin.jar weather-visual-inspection-plugin.jar
RUN rm -rf /usr/src/weather_visual_inspection_plugin/src
COPY config.json /usr/src/weather_visual_inspection_plugin/
COPY entrypoint.sh /usr/src/weather_visual_inspection_plugin
WORKDIR /usr/src/weather_visual_inspection_plugin
ENTRYPOINT ["./entrypoint.sh"]
